spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile

  cloud:
    gateway:
      default-filters:
        - SaveSession
        - RemoveRequestHeader=Cookie
        - Jwt
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR
            methods: GET
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/catalog/books/**
        - id: search-route
          uri: ${SEARCH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/search/**
        - id: rental-route
          uri: ${RENTAL_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/rental/**
        - id: user-profiles-route
          uri: ${USER_PROFILES_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/user-profiles/**

  data:
    mongodb:
      authentication-database: sessions
      host: ${mongo.server.url:localhost}
      port: ${mongo.server.port:28017}
      username: ${mongo.username:root}
      password: ${mongo.password:root1}
      database: sessions
  session:
    store-type: mongodb
    timeout: 10m

catalog:
  service:
    url: ${CATALOG_SERVICE_URL:http://localhost:8082}
rental:
  service:
    url: ${RENTAL_SERVICE_URL:http://localhost:8083}
inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8084}
user-profiles:
  service:
    url: ${USER_PROFILES_SERVICE_URL:http://localhost:8085}
