spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:817921738258-cp6qkk9avb03ciibflfltdjdummgqb5p.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope: openid, profile, email
        provider:
          google:
            issuer-uri: accounts.google.com

  cloud:
    gateway:
      default-filters:
        - SaveSession
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR
            methods: GET
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/catalog/books/**
        - id: search-route
          uri: ${SEARCH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/search/**
        - id: rental-route
          uri: ${RENTAL_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/rental/**
          filters:
            - name: TokenRelay

  redis:
    connection-timeout: 30s
    host: localhost
    port: 6379
    timeout: 5s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: library:gateway

catalog:
  service:
    url: ${CATALOG_SERVICE_URL:http://localhost:8082}
rental:
  service:
    url: ${RENTAL_SERVICE_URL:http://localhost:8083}
inventory:
  service:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8084}