spring:
  cloud:
    gateway:
      routes:
        - id: catalog_route
          uri: http://10.156.15.210:8081
          predicates:
            - Path=/api/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false