spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR
            methods: GET
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/catalog/books/**
        - id: search-route
          uri: ${SEARCH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/search/**
        - id: rental-route
          uri: ${RENTAL_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/rental/**